// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoRabatexOficial.Models;

#nullable disable

namespace ProyectoRabatexOficial.Migrations
{
    [DbContext(typeof(DbProyectoRabatexContext))]
    [Migration("20230113213936_MySecondMigration")]
    partial class MySecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<double>("Monto")
                        .HasColumnType("float")
                        .HasColumnName("monto");

                    b.HasKey("Id");

                    b.ToTable("Caja", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Egreso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Egreso", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Ingreso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Ingreso", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.IngresoCliente", b =>
                {
                    b.Property<int>("IdRelacion")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdIngreso")
                        .HasColumnType("int");

                    b.HasKey("IdRelacion");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdIngreso");

                    b.ToTable("ProductoCliente", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.IngresoProducto", b =>
                {
                    b.Property<int>("IdRelacion")
                        .HasColumnType("int");

                    b.Property<int>("IdIngreso")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<float>("cantidad")
                        .HasColumnType("real")
                        .HasColumnName("cantidad");

                    b.HasKey("IdRelacion");

                    b.HasIndex("IdIngreso");

                    b.HasIndex("IdProducto");

                    b.ToTable("IngresoProducto", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Stock")
                        .HasColumnType("float")
                        .HasColumnName("stock");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.StockProducto", b =>
                {
                    b.Property<int>("IdRelacion")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdStock")
                        .HasColumnType("int");

                    b.HasKey("IdRelacion");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdStock");

                    b.ToTable("StockProducto", (string)null);
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.IngresoCliente", b =>
                {
                    b.HasOne("ProyectoRabatexOficial.Models.Cliente", "IdClienteNavigation")
                        .WithMany("IngresoClientes")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_ProductoCliente_Cliente");

                    b.HasOne("ProyectoRabatexOficial.Models.Ingreso", "IdIngresoNavigation")
                        .WithMany("IngresoClientes")
                        .HasForeignKey("IdIngreso")
                        .IsRequired()
                        .HasConstraintName("FK_ProductoCliente_Producto");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdIngresoNavigation");
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.IngresoProducto", b =>
                {
                    b.HasOne("ProyectoRabatexOficial.Models.Ingreso", "IdIngresoNavigation")
                        .WithMany("IngresoProductos")
                        .HasForeignKey("IdIngreso")
                        .IsRequired()
                        .HasConstraintName("FK_IngresoProducto_Ingreso");

                    b.HasOne("ProyectoRabatexOficial.Models.Producto", "IdProductoNavigation")
                        .WithMany("IngresoProductos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_IngresoProducto_Producto");

                    b.Navigation("IdIngresoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.StockProducto", b =>
                {
                    b.HasOne("ProyectoRabatexOficial.Models.Producto", "IdProductoNavigation")
                        .WithMany("StockProductos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_StockProducto_Producto");

                    b.HasOne("ProyectoRabatexOficial.Models.Stock", "IdStockNavigation")
                        .WithMany("StockProductos")
                        .HasForeignKey("IdStock")
                        .IsRequired()
                        .HasConstraintName("FK_StockProducto_Stock");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdStockNavigation");
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Cliente", b =>
                {
                    b.Navigation("IngresoClientes");
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Ingreso", b =>
                {
                    b.Navigation("IngresoClientes");

                    b.Navigation("IngresoProductos");
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Producto", b =>
                {
                    b.Navigation("IngresoProductos");

                    b.Navigation("StockProductos");
                });

            modelBuilder.Entity("ProyectoRabatexOficial.Models.Stock", b =>
                {
                    b.Navigation("StockProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
